name: contractguard-sut

services:
  sut:
    image: sut:dev
    container_name: contractguard-sut
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://contractguard:password@postgres:5432/contractguard
      REDIS_URL: redis://redis:6379/0
      NATS_URL: nats://nats:4222
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      AUTH_MODE: static
      LOG_LEVEL: DEBUG
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      nats:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 5s
      timeout: 3s
      retries: 3

  postgres:
    image: pgvector/pgvector:pg16
    container_name: contractguard-postgres
    environment:
      POSTGRES_USER: contractguard
      POSTGRES_PASSWORD: password
      POSTGRES_DB: contractguard
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U contractguard"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: contractguard-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  nats:
    image: nats:2.10-alpine
    container_name: contractguard-nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js", "-m", "8222"]

  minio:
    image: minio/minio:latest
    container_name: contractguard-minio
    # ports:
    #   - "9000:9000"
    #   - "9001:9001"
    ports:
      - "9100:9000"  # Changed from 9000:9000
      - "9101:9001"  # Changed from 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  otel-collector:
    image: otel/opentelemetry-collector:0.91.0
    container_name: contractguard-otel
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"
      - "4317:4317"

  jaeger:
    image: jaegertracing/all-in-one:1.53
    container_name: contractguard-jaeger
    ports:
      - "16686:16686"
      - "14268:14268"

  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: contractguard-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:10.2.3
    container_name: contractguard-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  postgres-data:
  minio-data:
  prometheus-data:
  grafana-data:
